# Generated by Django 3.0.3 on 2020-03-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('type', models.CharField(choices=[('K', 'Kawiarnia'), ('R', 'Restauracja'), ('B', 'Bar'), ('I', 'Inna')], max_length=264)),
                ('form', models.CharField(choices=[('KP', 'Karta podarunkowa'), ('Z', 'Zniżka'), ('ZAW', 'Zawieszony produkt (np.kawa)"'), ('I', 'Inna')], max_length=264)),
                ('url', models.URLField(unique=True)),
                ('city', models.CharField(max_length=264)),
                ('update_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=264)),
                ('starting_date', models.DateField()),
            ],
        ),
    ]
