# Generated by Django 3.0.3 on 2020-03-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('type', models.CharField(choices=[('Kawiarnia', 'Kawiarnia'), ('Restauracja', 'Restauracja'), ('Bar', 'Bar'), ('Inna', 'Inna')], max_length=264)),
                ('form', models.CharField(choices=[('Karta podarunkowa', 'Karta podarunkowa'), ('Zniżka', 'Zniżka'), ('Zawieszony produkt', 'Zawieszony produkt (np.kawa)'), ('Inna', 'Inna')], max_length=264)),
                ('url', models.URLField()),
                ('city', models.CharField(max_length=264)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=264)),
                ('starting_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Subscribers',
            },
        ),
    ]
