# Generated by Django 3.0.3 on 2020-04-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True, verbose_name='Nazwa')),
                ('type', models.CharField(choices=[('Kawiarnia', 'Kawiarnia'), ('Restauracja', 'Restauracja'), ('Bar', 'Bar'), ('Mały biznes', 'Mały biznes'), ('Księgarnia', 'Księgarnia'), ('Sklep z ubraniami', 'Sklep z ubraniami'), ('Sklep plastyczny', 'Sklep plastyczny'), ('Zoo', 'Zoo'), ('Sklep dla zwierząt', 'Sklep dla zwierząt'), ('Piekarnia', 'Piekarnia'), ('Sklep krawiecki', 'Sklep krawiecki'), ('Bazar', 'Bazar'), ('Garmażeria', 'Garmażeria'), ('Bar mleczny', 'Bar mleczny'), ('Kino', 'Kino'), ('Inny', 'Inny')], max_length=264, verbose_name='Kategoria')),
                ('form', models.CharField(choices=[('Karta podarunkowa', 'Karta podarunkowa'), ('Zniżka', 'Zniżka'), ('Zawieszony produkt', 'Zawieszony produkt (np.kawa)'), ('Produkt', 'Produkt'), ('Subskrypcja', 'Subskrypcja'), ('Zakupy online', 'Zakupy online'), ('Inna', 'Inna')], max_length=264, verbose_name='Rodzaj wsparcia')),
                ('url', models.URLField(verbose_name='URL')),
                ('city', models.CharField(max_length=264, verbose_name='Miasto')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=264, verbose_name='Imię')),
                ('starting_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Subscribers',
            },
        ),
    ]
