# Generated by Django 3.0.3 on 2020-04-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
