# Generated by Django 3.0.3 on 2020-03-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'verbose_name_plural': 'Newsletter Subscribers'},
        ),
    ]
