# Generated by Django 3.0.3 on 2020-03-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('Kawiarnia', 'Kawiarnia'), ('Restauracja', 'Restauracja'), ('Bar', 'Bar'), ('Inny', 'Inny')], max_length=264),
        ),
    ]
