# Generated by Django 3.0.3 on 2020-03-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='starting_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
