# Generated by Django 3.0.3 on 2020-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_application', '0002_auto_20200331_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='form',
            field=models.CharField(choices=[('Karta podarunkowa', 'Karta podarunkowa'), ('Zniżka', 'Zniżka'), ('Zawieszony produkt', 'Zawieszony produkt (np.kawa)'), ('Inna', 'Inna')], max_length=264, verbose_name='Forma'),
        ),
    ]
