# Generated by Django 3.0.3 on 2020-04-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_application', '0003_auto_20200404_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(max_length=264, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='business',
            name='form',
            field=models.CharField(choices=[('Karta podarunkowa', 'Karta podarunkowa'), ('Zniżka', 'Zniżka'), ('Zawieszony produkt', 'Zawieszony produkt (np.kawa)'), ('Inna', 'Inna')], max_length=264, verbose_name='Rodzaj wsparcia'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=264, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('Kawiarnia', 'Kawiarnia'), ('Restauracja', 'Restauracja'), ('Bar', 'Bar'), ('Inny', 'Inny')], max_length=264, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='business',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
