# Generated by Django 3.0.3 on 2020-04-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_application', '0004_auto_20200404_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='name',
            field=models.CharField(max_length=264, verbose_name='Imię'),
        ),
    ]
