# Generated by Django 3.0.3 on 2020-04-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_application', '0005_auto_20200404_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='form',
            field=models.CharField(choices=[('Karta podarunkowa', 'Karta podarunkowa'), ('Zniżka', 'Zniżka'), ('Zawieszony produkt', 'Zawieszony produkt (np.kawa)'), ('Produkt', 'Produkt'), ('Subskrypcja', 'Subskrypcja'), ('Zakupy online', 'Zakupy online'), ('Inna', 'Inna')], max_length=264, verbose_name='Rodzaj wsparcia'),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('Kawiarnia', 'Kawiarnia'), ('Restauracja', 'Restauracja'), ('Bar', 'Bar'), ('Mały biznes', 'Mały biznes'), ('Księgarnia', 'Księgarnia'), ('Sklep z ubraniami', 'Sklep z ubraniami'), ('Sklep plastyczny', 'Sklep plastyczny'), ('Zoo', 'Zoo'), ('Sklep dla zwierząt', 'Sklep dla zwierząt'), ('Piekarnia', 'Piekarnia'), ('Sklep krawiecki', 'Sklep krawiecki'), ('Bazar', 'Bazar'), ('Garmażeria', 'Garmażeria'), ('Bar mleczny', 'Bar mleczny'), ('Kino', 'Kino'), ('Inny', 'Inny')], max_length=264, verbose_name='Kategoria'),
        ),
    ]
